FROM node:21-alpine3.17 as builder
LABEL stage=builder
WORKDIR /app/
COPY . /app/
RUN npm install && npm run prod

FROM node:21-alpine3.17
WORKDIR /app/
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/dist ./dist/
RUN npm ci --only=production

ENTRYPOINT [ "npm" ]
CMD [ "run", "start:prod" ]
EXPOSE 3000